version: '3.8'
services:
  backend:
    build:
      context: ./
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    restart: always
    ports:
      - "3000:4003"
    environment:
      NODE_ENV: development
